variable access_key  {default=""}
variable secret_key  {default=""}
variable region  { default="us-east-1"}
variable ami_id  { default="ami-6d1c2007"}
variable key_name  {default=""}
variable key_file  {default=""}
variable sds_count {default="3"}
variable sds_instance_type {default="r3.2xlarge"}
variable mdm_instance_type {default="m3.medium"}
